//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./DotNet.CompiladoresProjetoFinal.App/ANTLR/VariableDeclaration.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VariableDeclarationParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IVariableDeclarationListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VariableDeclarationParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] VariableDeclarationParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VariableDeclarationParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] VariableDeclarationParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VariableDeclarationParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] VariableDeclarationParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VariableDeclarationParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] VariableDeclarationParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VariableDeclarationParser.declaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaratorList([NotNull] VariableDeclarationParser.DeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VariableDeclarationParser.declaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaratorList([NotNull] VariableDeclarationParser.DeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VariableDeclarationParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] VariableDeclarationParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VariableDeclarationParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] VariableDeclarationParser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VariableDeclarationParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] VariableDeclarationParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VariableDeclarationParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] VariableDeclarationParser.InitializerContext context);
}
